In [1]:
import jax
from calm.environment import MiniHackWrapper, UndictWrapper
import numpy as np
import gym
from gym.wrappers.autoreset import AutoResetWrapper
import gym.vector
import minihack
from nle import nethack
from calm.environment import ShaperWrapper

actions = [
    nethack.CompassCardinalDirection.N,
    nethack.CompassCardinalDirection.E,
    nethack.CompassCardinalDirection.S,
    nethack.CompassCardinalDirection.W,
    nethack.Command.PICKUP,
    nethack.Command.APPLY,
]
observation_key = "chars_crop"
env = gym.make(
    "MiniHack-KeyRoom-S5-v0",
    actions=actions,
    observation_keys=(
        observation_key,
        "glyphs",
        "chars",
        "chars_crop",
        "message",
        "inv_glyphs",
        "blstats",
        "screen_descriptions"
    ),
    max_episode_steps=100,
    seeds=[0],
)
env = ShaperWrapper(env)
obs, info = env.reset()
env.render()

/home/uceeepi/miniforge3/envs/nle/lib/python3.9/site-packages/gym/envs/registration.py:307: DeprecationWarning: The package name gym_minigrid has been deprecated in favor of minigrid. Please uninstall gym_minigrid and install minigrid with `pip install minigrid`. Future releases will be maintained under the new package name minigrid.
  fn()
/home/uceeepi/.local/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm



You are lucky!  Full moon tonight.                                              
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                       ----                                     
                                       |..|                                     
                                       |@.|                                     
                           

/home/uceeepi/miniforge3/envs/nle/lib/python3.9/site-packages/jax/_src/api_util.py:174: SyntaxWarning: Jitted function has static_argnums=(0, 3), but only accepts 3 positional arguments. This warning will be replaced by an error after 2022-08-20 at the earliest.
  warnings.warn(f"Jitted function has {argnums_name}={argnums}, "
/home/uceeepi/miniforge3/envs/nle/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:31: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy to properly process the data. Actual observation shape: (21, 79)
  logger.warn(
/home/uceeepi/miniforge3/envs/nle/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:31: UserWarning: WARN: A Box observation space has an unconventional shape (neither an image, nor a 1D vector). We recommend flattening the observation to have only a 1D vector or use a custom policy t

In [10]:
obs, reward, term, trunc, info = env.step(5)
print("Reward:", reward)
env.render()

check if door is open already
check if action is APPLY
check if message is the one we are looking for
[ 78 101 118 101 114  32 109 105 110 100  46]
[ 78 101 118 101 114  32 109 105 110 100  46]
check if door has been opened by the current action
Reward: 0.99

Never mind.                                                                     
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
           

In [10]:
obs["message"]

array([ 78, 101, 118, 101, 114,  32, 109, 105, 110, 100,  46,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [81]:
obs_before = np.copy(obs["glyphs"])

In [83]:
obs_after = obs["glyphs"]

In [85]:
import numpy as np

obs_before[obs_before != obs_after]

array([2359, 2359, 2359, 2359, 2359, 2359, 2374, 2359, 2359, 2362],
      dtype=int16)

In [89]:
obs_after[obs_before != obs_after]

array([2362, 2361, 2361, 2360, 2378, 2378, 2372, 2360, 2383, 2370],
      dtype=int16)

In [88]:
door_glyph = [2374, 2362]

In [11]:
def f(x):
    return "".join([chr(a) for a in x])

glyphs = obs["glyphs"].reshape(-1)
for i, tile in enumerate(obs["screen_descriptions"].reshape(-1, 80)):
    name = f(tile)
    if "door" in name:
        glyph = glyphs[i]
        print(glyph, name)

2373 open door


In [15]:
True + True

2

In [18]:
env.reward_range

(-inf, inf)